from ..types.currency import Currency

#
# Constants
#

AED = Currency('AED')
ARS = Currency('ARS')
AUD = Currency('AUD')
BDT = Currency('BDT')
BHD = Currency('BHD')
BRL = Currency('BRL')
BTC = Currency('BTC')
CAD = Currency('CAD')
CHF = Currency('CHF')
CLP = Currency('CLP')
CNY = Currency('CNY')
COP = Currency('COP')
CZK = Currency('CZK')
DKK = Currency('DKK')
EGP = Currency('EGP')
ETH = Currency('ETH')
EUR = Currency('EUR')
GBP = Currency('GBP')
HKD = Currency('HKD')
HUF = Currency('HUF')
IDR = Currency('IDR')
ILS = Currency('ILS')
INR = Currency('INR')
ISK = Currency('ISK')
JPY = Currency('JPY')
KES = Currency('KES')
KRW = Currency('KRW')
KWD = Currency('KWD')
LKR = Currency('LKR')
MAD = Currency('MAD')
MXN = Currency('MXN')
MYR = Currency('MYR')
NGN = Currency('NGN')
NOK = Currency('NOK')
NONE = Currency('NONE')
NZD = Currency('NZD')
PEN = Currency('PEN')
PHP = Currency('PHP')
PKR = Currency('PKR')
PLN = Currency('PLN')
QAR = Currency('QAR')
RON = Currency('RON')
RSD = Currency('RSD')
RUB = Currency('RUB')
SAR = Currency('SAR')
SEK = Currency('SEK')
SGD = Currency('SGD')
THB = Currency('THB')
TND = Currency('TND')
TRY = Currency('TRY')
TWD = Currency('TWD')
USD = Currency('USD')
USDT = Currency('USDT')
VES = Currency('VES')
VND = Currency('VND')
ZAR = Currency('ZAR')
